[PHP]
memory_limit = 512M ; LiteSpeed版の恩恵を受けるために少し多めに
post_max_size = 100M
upload_max_filesize = 100M
date.timezone = "Asia/Tokyo"

# PHP 8.4 用の最適化設定（任意）
opcache.enable=1
opcache.jit=tracing
opcache.jit_buffer_size=128M